# Generated by Django 5.0.6 on 2026-06-18 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0074_firstreviewremark_secondreviewremark_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Team',
        ),
    ]
