# Generated by Django 5.0.6 on 2026-06-18 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0076_team'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Team',
        ),
    ]
