# Generated by Django 5.0.6 on 2026-06-18 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0077_delete_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('student_class', models.CharField(max_length=50)),
                ('domain', models.CharField(blank=True, max_length=100, null=True)),
                ('members', models.TextField()),
                ('member_names', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('leader_id', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('pending_update', 'Pending Update'), ('approved', 'Approved')], default='pending', max_length=20)),
                ('needs_update_problem', models.BooleanField(default=False)),
                ('needs_update_domain', models.BooleanField(default=False)),
                ('needs_update_members', models.BooleanField(default=False)),
                ('modification_reason', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'team',
            },
        ),
    ]
