# Generated by Django 5.0.6 on 2026-07-06 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0078_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.IntegerField()),
                ('annotation_type', models.CharField(choices=[('highlight', 'Highlight'), ('comment', 'Comment')], default='highlight', max_length=20)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('width', models.FloatField()),
                ('height', models.FloatField()),
                ('color', models.CharField(default='#FFFF00', max_length=20)),
                ('selected_text', models.TextField(blank=True)),
                ('comment', models.TextField(blank=True)),
                ('mentor', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='allocation.projectfile')),
            ],
            options={
                'ordering': ['page_number', 'created_at'],
            },
        ),
    ]
