# Generated by Django 5.0.6 on 2026-07-06 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0079_annotation'),
    ]

    operations = [
        migrations.AddField(
            model_name='zerothreviewremark',
            name='coordinates',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='zerothreviewremark',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='zerothreviewremark',
            name='color',
            field=models.CharField(default='#ffe066', max_length=20),
        ),
        migrations.AlterField(
            model_name='zerothreviewremark',
            name='file_type',
            field=models.CharField(default='abstract', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='zerothreviewremark',
            unique_together={('team_name', 'mentor_name', 'heading')},
        ),
    ]
