# Generated by Django 5.0.6 on 2026-07-06 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0080_zerothreviewremark_coordinates_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zerothreviewremark',
            name='coordinates',
            field=models.TextField(blank=True, default='{}'),
        ),
    ]
