# Generated by Django 5.0.6 on 2026-07-06 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0081_alter_zerothreviewremark_coordinates'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ZerothReviewRemark',
        ),
    ]
