# Generated by Django 5.0.6 on 2026-07-06 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0082_delete_zerothreviewremark'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZerothReviewRemark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=255)),
                ('mentor_name', models.CharField(max_length=255)),
                ('heading', models.CharField(max_length=255)),
                ('remark', models.TextField()),
                ('color', models.CharField(default='#ffe066', max_length=20)),
                ('file_type', models.CharField(default='abstract', max_length=20)),
                ('coordinates', models.TextField(blank=True, default='{}')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('team_name', 'mentor_name', 'heading')},
            },
        ),
    ]
