# Generated by Django 5.0.6 on 2026-07-12 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0083_zerothreviewremark'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Team',
        ),
    ]
