# Generated by Django 5.0.6 on 2026-07-12 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0085_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='HOD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('department', models.CharField(default='CSE', max_length=80)),
                ('email', models.EmailField(blank=True, max_length=120, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('joined_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='HOD_Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=80, unique=True)),
                ('password', models.CharField(max_length=80)),
            ],
        ),
    ]
